### PR TITLE
Add HexString -> Maybe Int + Tests

### PR DESCRIPTION
**Pull request by cmditch**

### CODE REVIEW

**Comment by blinky3713** [comment]
I'm not really sure this is what you want to do here. We already have 

```haskell
parseBigNumber :: Int.Radix -> String -> Maybe BigNumber
```

and an unsafe function

```haskell
toInt :: BigNumber -> Int
```

so you can recover your changes already from those. Is there something specific you want to do that you can't do with these?

Another problem is that most likely your hex string is going to overflow.

**Comment by cmditch** [comment]
The intention behind this was to help with turn the block number into something readable. You're right, what I'm trying to achieve is totally doable using existing functions.

e.g., `0x44DA4C  to  "4,512,332"`

Using `toInt :: HexString -> Maybe Int`
```haskell
blockNumber :: String
blockNumber = maybe "Error parsing block number" (format commaSeperate) blockNum
  where
    blocknum = Int.toNumber <$> (Utils.toInt state.blockNumber)
```

Using existing functions
```haskell
blockNumber :: String
blockNumber = maybe "Error parsing block number" (format commaSeperate) blockNum
  where
    blockNum = Utils.toNumber $ BN.fromHexString state.blockNumber
```

**Comment by cmditch** [comment]
Though the above would only work if `Network.Ethereum.Web3.Types.BigNumber.toNumber` was exposed.

`unsafeToInt` is exposed, but no reason to the above with `HexString -> BigNumber -> unsafeInt -> Number -> String` when `HexString -> BigNumber -> Number -> String` can be achieved.

 Thoughts?

**Comment by blinky3713** [comment]
you can use 
```haskell
foreign import fromHexString :: HexString -> BigNumber
```

and call show on that if you want something readable. It prints in base 10

**Comment by cmditch** [comment]
Good deal. Thanks

**Pull request closed without merging**
