### PR TITLE
Mixed case & odd length HexStrings 

### LINKED ISSUE #45: Parsing of mixed case hexstrings fails
We used to be able to parse hex-strings such as `0xAbCd`, now we're failing on this.
My suspicion is that this was maybe introduced with #36 but I haven't verified that.

Why do we want to be able to parse mixed case strings? See https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

Of course, we should likely implement this feature in the in the `Address` constructor and throw there instead.

### PR DESCRIPTION
**Pull request by XertroV**
* [x] Add test for mixed case HexStrings
* [x] Add test for odd-lengthed HexStrings
* [x] Implement solution for mixed case
* [x] Implement soln for odd-lengthed
* [x] Add `toLower` to `Eq` instance of `HexString`

Fixes #45

### CODE REVIEW

**Comment by XertroV** [comment]
@blinky3713 & @kejace - have finished this PR

**Comment by blinky3713** [comment]
Hey @XertroV this looks good. Can we go ahead and get the proper equality done in this pr where equality is checked on lower case values like you suggested?

**Comment by XertroV** [comment]
Yeah probs good idea. Ethereum might return checksummed addresses sometimes and not others, for example. Since we deserialize automagically we want toLower in the eq instance too.

**Comment by XertroV** [comment]
@blinky3713 - fixed up `Eq HexString` now.

**Pull request merged**
